INSERT INTO ticTacToe.game_Lobby (Rank_1, Rank_2, UID_1, UID_2, Username_1, Username_2, TopLeft, TopCenter, TopRight, MiddleLeft, MiddleCenter, MiddleRight, BottomLeft, BottomCenter, BottomRight) VALUES (
	'1',
	'2',
	'1',
	'2',
	'pikachu',
	'bulbasaur',
	'UID_1',
	'UID_2',
	'none',
	'none',
	'UID_1',
	'none',
	'UID_2',
	'none',
	'none');
